
#ifndef MG_INPUT_H
#define MG_INPUT_H

typedef enum key {
    M_KEY_A,
    M_KEY_B,
    M_KEY_C,
    M_KEY_D,
    M_KEY_E,
    M_KEY_F,
    M_KEY_G,
    M_KEY_H,
    M_KEY_I,
    M_KEY_J,
    M_KEY_K,
    M_KEY_L,
    M_KEY_M,
    M_KEY_N,
    M_KEY_O,
    M_KEY_P,
    M_KEY_Q,
    M_KEY_R,
    M_KEY_S,
    M_KEY_T,
    M_KEY_U,
    M_KEY_V,
    M_KEY_W,
    M_KEY_X,
    M_KEY_Y,
    M_KEY_Z,
    M_KEY_0,
    M_KEY_1,
    M_KEY_2,
    M_KEY_3,
    M_KEY_4,
    M_KEY_5,
    M_KEY_6,
    M_KEY_7,
    M_KEY_8,
    M_KEY_9,
    M_KEY_GRAVE,
    M_KEY_MINUS,
    M_KEY_EQUALS,
    M_KEY_COMMA,
    M_KEY_PERIOD,
    M_KEY_SLASH,
    M_KEY_SEMICOLON,
    M_KEY_QUOTE,
    M_KEY_LBRACKET,
    M_KEY_RBRACKET,
    M_KEY_BACKSLASH,
    M_KEY_SPACE,
    M_KEY_LSHIFT,
    M_KEY_RSHIFT,
    M_KEY_ESC,
    M_KEY_RETURN,
    M_KEY_BACKSPACE,
    M_KEY_DELETE,
    M_KEY_TAB,
    M_KEY_LCTRL,
    M_KEY_RCTRL,
    M_KEY_LALT,
    M_KEY_RALT,
    M_KEY_LMETA,
    M_KEY_RMETA,
    M_KEY_LEFT,
    M_KEY_RIGHT,
    M_KEY_UP,
    M_KEY_DOWN,
} key;

int key_to_rl(key k);

#endif // MG_INPUT_H